### ISSUE TITLE
Error scanning for devices

### ISSUE THREAD

**Issue by gomesfmp** [hassio-addons/addon-tasmoadmin#244]
# Problem/Motivation

> scanning for devices

## Expected behavior

> show all scanned devices

## Actual behavior

> error: [/var/www/tasmoadmin/tasmoadmin/tmp/cache/i18n/php_i18n_16dff9cb66d1ffd73722a1bb89ef4fca___L_en.cache.php on line 421](https://192.xxx.xxx.xxx:9541/devices_autoscan#)

## Steps to reproduce

> Go to devices, AutoScan, fill ip range, start autoscan
![Capture](https://user-images.githubusercontent.com/104598966/173257693-2a29d652-f1b6-4044-a6ee-386a9c69e81c.JPG)

**Comment by inverse** [comment]
What version of the add-on are you running?

**Comment by gomesfmp** [comment]
Version 0.19.0

**Comment by Cul8rch** [comment]
I have the same issue with the last and also the newest version.

**Comment by stuarts0011** [comment]
> I have the same issue with the last and also the newest version.

Me too

**Comment by davebeckster** [comment]
**** TasmoAdmin to v2.0.0-beta6 ****
Home Assistant Core 2022.6.6
Home Assistant Supervisor 2022.05.3
Home Assistant OS 8.2

[/var/www/tasmoadmin/tasmoadmin/tmp/cache/i18n/php_i18n_16dff9cb66d1ffd73722a1bb89ef4fca___L_en.cache.php on line 421](http://192.168.86.27:9541/devices_autoscan#)

Fatal error: Uncaught Error: Call to undefined function iconv_strlen() in /var/www/tasmoadmin/tasmoadmin/vendor/symfony/polyfill-mbstring/Mbstring.php:491 Stack trace: #0 /var/www/tasmoadmin/tasmoadmin/vendor/symfony/polyfill-mbstring/bootstrap80.php(57): Symfony\Polyfill\Mbstring\Mbstring::mb_strlen() #1 /var/www/tasmoadmin/tasmoadmin/vendor/erusev/parsedown/Parsedown.php(170): mb_strlen() #2 /var/www/tasmoadmin/tasmoadmin/vendor/erusev/parsedown/Parsedown.php(39): Parsedown->lines() #3 /var/www/tasmoadmin/tasmoadmin/vendor/erusev/parsedown/Parsedown.php(1580): Parsedown->text() #4 /var/www/tasmoadmin/tasmoadmin/pages/selfupdate.php(42): Parsedown->parse() #5 /var/www/tasmoadmin/tasmoadmin/index.php(55): include_once('...') #6 {main} thrown in /var/www/tasmoadmin/tasmoadmin/vendor/symfony/polyfill-mbstring/Mbstring.php on line 491

**Comment by kierenblack** [comment]
I am having the same issue. I have the latest version, 0.19. Are there any updates?

**Comment by inverse** [comment]
![image](https://user-images.githubusercontent.com/713525/174401321-cfb517f9-3a34-4e02-aeb3-12db698c84ce.png)

I'm unable to reproduce on a fresh install of `0.19` from the appstore.

**Comment by Cul8rch** [comment]
I found out, that it depends on the devices which will be recognized. A single Sonoff miniR2 works fine. As soon as I take the Sonoff Dual R3 into the Network the Error occures. An the error log above states something with string lenght I tried to shorten the device name with no success. All devices are on Tasmota.

**Comment by inverse** [comment]
@Cul8rch is there anything in the PHP error log of the container?

If you use https://github.com/hassio-addons/addon-ssh in privileged mode you should be able to see with something like

```
docker exec -it addon_a0d7b954_sonweb cat /var/log/php8/error.log 
```

replacing `addon_a0d7b954_sonweb` with the correct ID of your docker container which can be found with `docker ps | grep sonweb`

**Comment by Cul8rch** [comment]
@inverse the output states: 
NOTICE: fpm is running. pid 173
NOTICE: ready to handle connections

**Comment by inverse** [comment]
@Cul8rch  Hmm I guess we need to redirect output to that file by setting `catch_workers_output = yes` in the fpm config.

It's hard to see what the error that you're currently seeing :/ line 421 in that file for me is

```
$return = constant("__L::".$string);
```

Which is strange as the initial screenshot in this report looks like it is erroring when printing out this code https://github.com/TasmoAdmin/TasmoAdmin/blob/2bcdc9e361ccdc1bb65a1ce3470f184ca0e544e2/tasmoadmin/pages/devices_autoscan.php#L291

Which doesn't use any localization :/

@frenck is that advised in these containers?

**Comment by Cul8rch** [comment]
@inverse sorry I an not that deep into the linux world (Windows is my homebase). If you could guide me where to find that config file I will add that output addition. I guess you are talking about php-fpm.config but I an not able to find that file in HA via the terminal or the host.
To be precise my error reads: [/var/www/tasmoadmin/tasmoadmin/tmp/cache/i18n/php_i18n_16dff9cb66d1ffd73722a1bb89ef4fca___L_de.cache.php on line 424](http://192.168.1.44:9541/devices_autoscan#)

**Comment by jan-gerard** [comment]
I have the same issue, only it does not appear directly. I an start Autoscan, then the new device is listed, but with an error, and I cannot find a way to click anything in order to add this device.
![2022-06-19_17-49-31](https://user-images.githubusercontent.com/7569832/174489528-f2b1fb6a-c0f8-4b6b-87f9-5d1cac8ab025.png)
Also, manually adding the device does not work, via the Devices > List page. "+ Add Device" brings me to the screen where I can enter the IP address of the device, but when I enter that and press Search, I get an empty screen. The browser debugger shows "http://192.168.x.x:9541/device_action/add" --> "500 Internal Server Error". No device is added.

**Comment by ralfm12** [comment]
I have the same error screen. This is always after a scan for new devices. I use ne 1.9 as the others.

**Comment by inverse** [comment]
@jan-gerard I think I figured out the issue you were facing and pushed a change 

Would you be able to run :

```
docker run -it -p 8000:80 ghcr.io/tasmoadmin/tasmoadmin:dev
```

And verify it's fixed? unfortunately you'll need to configure things again but it will be able to verify the issue your facing is fixed and I can push a fix to this addon.

**Comment by jan-gerard** [comment]
> 



> Would you be able to run :
> 
> ```
> docker run -it -p 8000:80 ghcr.io/tasmoadmin/tasmoadmin:dev
> ```
> 
> And verify it's fixed? unfortunately you'll need to configure things again but it will be able to verify the issue your facing is fixed and I can push a fix to this addon.

I tested it. Now I can add a device, manually. I no longer get an empty screen after I submit the IP address. And for a number of devices it works, but for some I still get the error message:
`[/var/www/tasmoadmin/tmp/cache/i18n/php_i18n_16dff9cb66d1ffd73722a1bb89ef4fca___L_en.cache.php on line 424](http://***:8000/device_action/add#)`
and when hovering that this pops up:
`Fatal error: Uncaught Error: Undefined constant __L::DEVICE_ACTIONS_OVERTAKE in /var/www/tasmoadmin/tmp/cache/i18n/php_i18n_16dff9cb66d1ffd73722a1bb89ef4fca___L_en.cache.php:424 Stack trace: #0 /var/www/tasmoadmin/tmp/cache/i18n/php_i18n_16dff9cb66d1ffd73722a1bb89ef4fca___L_en.cache.php(424): constant() #1 /var/www/tasmoadmin/includes/bootstrap.php(146): __L() #2 /var/www/tasmoadmin/pages/device_action.php(307): __() #3 /var/www/tasmoadmin/index.php(55): include_once(`

**Comment by inverse** [comment]
That looks like the exact error the others are reporting! Looks like it's trying to load a translation that doesn't exist and the bump from PHP 7.4 to 8 in this addon caused it to become visible. Will try and get a fix for that tomorrow.

**Comment by inverse** [comment]
@jan-gerard I used an existing translation which looks like it would make sense in this case.

New build should be ready after this pipeline: https://github.com/TasmoAdmin/TasmoAdmin/actions/runs/2531206812

Let me know if it resolves the issue and i'll tag a new release

**Comment by frenck** [comment]
Sorry didn't mean to close it yet. I did bump the add-on, but it seems v2.0.0-beta8 was re-tagged right after the add-on was updated. Re-tagging is problematic in any environment, as there are now 2 v2.0.0-beta8 versions 😞 

Filed: <https://github.com/TasmoAdmin/TasmoAdmin/issues/569>

**Comment by inverse** [comment]
@frenck published https://github.com/TasmoAdmin/TasmoAdmin/releases/tag/v2.0.0-beta9 which I wont retag (sorry) with some minor fixes

**Comment by frenck** [comment]
Has this issue been fixed with the latest release? As in, a confirmation is welcome :)

**Comment by jan-gerard** [comment]
How to test this version? Is that the same command?
`docker run -it -p 8000:80 ghcr.io/tasmoadmin/tasmoadmin:dev` ?

**Comment by frenck** [comment]
@jan-gerard No commands, just upgrade the add-on to v0.19.1

https://github.com/hassio-addons/addon-tasmoadmin/releases/tag/v0.19.1

**Comment by davebeckster** [comment]
I'm not a developer, but it appears to be fixed.

**Comment by frenck** [comment]
Good! Thanks, going to close this issue for now 👍

**Comment by gomesfmp** [comment]
Works like a charm! Thank you so much.

**Comment by frenck** [comment]
Nice thanks for letting us know! And yes; @inverse did a great job! 👍

**Comment by jan-gerard** [comment]
Yes, tested here as well, and now my Digoo DG-SP202 double smart plug works well. Thanks a lot for the quick fix.
